-- MySQL Script generated by MySQL Workbench
-- Tue Aug 11 04:52:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema delilah
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `delilah` ;

-- -----------------------------------------------------
-- Table `delilah`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`order` ;

CREATE TABLE IF NOT EXISTS `delilah`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `payment_method` ENUM('card', 'cash') NULL,
  `status` ENUM('cancelled', 'confirmed', 'delivered', 'in_prep', 'new', 'sent') NULL DEFAULT 'new',
  `del_flag` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `delilah`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`order_product` ;

CREATE TABLE IF NOT EXISTS `delilah`.`order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NULL DEFAULT 1,
  INDEX `fk_order_product_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_product_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `delilah`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `delilah`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`product` ;

CREATE TABLE IF NOT EXISTS `delilah`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  `price` FLOAT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`user` ;

CREATE TABLE IF NOT EXISTS `delilah`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `fullname` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `address` VARCHAR(255) NULL,
  `admin` TINYINT NULL DEFAULT 0,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

SET SQL_MODE = '';
DROP USER IF EXISTS delilah;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'delilah' IDENTIFIED BY '1234';

GRANT SELECT ON TABLE `delilah`.* TO 'delilah';
GRANT SELECT, INSERT, TRIGGER ON TABLE `delilah`.* TO 'delilah';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `delilah`.* TO 'delilah';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
